/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MonacoEditor {
    }
}
declare global {
    interface HTMLMonacoEditorElement extends Components.MonacoEditor, HTMLStencilElement {
    }
    var HTMLMonacoEditorElement: {
        prototype: HTMLMonacoEditorElement;
        new (): HTMLMonacoEditorElement;
    };
    interface HTMLElementTagNameMap {
        "monaco-editor": HTMLMonacoEditorElement;
    }
}
declare namespace LocalJSX {
    interface MonacoEditor {
    }
    interface IntrinsicElements {
        "monaco-editor": MonacoEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "monaco-editor": LocalJSX.MonacoEditor & JSXBase.HTMLAttributes<HTMLMonacoEditorElement>;
        }
    }
}
